# Generated by Django 4.2.4 on 2023-08-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pin',
        ),
    ]
