# Generated by Django 4.2.4 on 2023-08-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_delete_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='file',
            new_name='upload_image',
        ),
    ]
