# Generated by Django 4.2.4 on 2023-08-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_file_profile_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.CharField(max_length=100)),
                ('my_profile', models.CharField(max_length=100)),
                ('settings', models.CharField(max_length=100)),
                ('log_out', models.CharField(max_length=100)),
            ],
        ),
    ]
