# Generated by Django 4.2.4 on 2023-08-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
