# Generated by Django 4.2.4 on 2023-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default='25000', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
